spring:
  application:
    name: room-reservation-svc

logbook:
  format:
    style: http
  predicate:
    exclude:
      - path: "/v3/api-docs"
      - path: "/v3/api-docs/**"
      - path: "/swagger-ui/**"

management:
  endpoints:
    web:
      exposure:
        include: health